### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by oakmac** [jtiscione/chessboard3js#1]
I just wanted to say that this project is awesome and I'm honored / humbled that you were able to mirror the [chessboard.js](https://github.com/oakmac/chessboardjs) API to a completely different rendering output.

Great work :) (and thanks for all the shout-outs!)

Chris Oakman
[oakmac](https://github.com/oakmac)

**Comment by jtiscione** [comment]
Thanks, Chris!

Your library made this much easier- having an API spec that I knew would
work. Plus there's a lot of client code out there that uses chessboard.js,
so I had my test environments all set up for me already. I might not have
bothered otherwise.

I stuck a copy on codepen.io last night but nobody's looked at it yet. How
do you publicize stuff like this once you're finished? I didn't even think
about it until now.

Jason
